### ISSUE TITLE
Mocks

### ISSUE THREAD

**Issue by raptorxcz** [WANGjieJacques/CodeGenerator#1]
Hi,

great work! The mock generator generates variable `xWasCalled: Bool?` I think `Int` is better because when the method is called twice the mock will not succeed.

Generating mock from text selection is not possible or it is a bug?

Thank you

**Comment by wangjiejacques** [comment]
Hi, @raptorxcz you are right for the `xWasCalled: Bool?`, but instead of replacing `Bool?` by `Int`, I will add another variable `xWasCalledTimes: Int`.

for now, generating mock from text selection is not possible.
